apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: abayer-jx-demo-qs-master-1
  namespace: jx
spec:
  params: []
  resources:
  - name: abayer-jx-demo-qs-master
    type: git
  tasks:
  - name: from-build-pack
    resources:
      inputs:
      - name: workspace
        resource: abayer-jx-demo-qs-master
    taskRef:
      name: abayer-jx-demo-qs-master-from-build-pack-1
status: {}
