apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: abayer-js-test-repo-really-long-1
  namespace: jx
spec:
  params: []
  resources:
  - name: abayer-js-test-repo-really-long
    type: git
  tasks:
  - name: build-a-really-long-stage-name-please-but-not-too-long-thanks
    resources:
      inputs:
      - name: workspace
        resource: abayer-js-test-repo-really-long
      outputs:
      - name: workspace
        resource: abayer-js-test-repo-really-long
    taskRef:
      name: abayer-js-test-repo-really-long-build-a-really-long-stage-nam-1
  - name: second
    resources:
      inputs:
      - from:
        - build-a-really-long-stage-name-please-but-not-too-long-thanks
        name: workspace
        resource: abayer-js-test-repo-really-long
    runAfter:
      - build-a-really-long-stage-name-please-but-not-too-long-thanks
    taskRef:
      name: abayer-js-test-repo-really-long-second-1
status: {}
